apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hfhj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hfhj
    app.kubernetes.io/part-of: cin4s-839-0007-app
  name: devfile-sample-hfhj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hfhj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hfhj
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0007-tenant/cin4s-839-0007-app/devfile-sample-hfhj@sha256:ec912fc851a25346294539a5246cd515f3fdfe066c56eb3c50fd4d4974729375
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
